
services:

  openbas:
    image: openbas/platform:1.9.0
    environment:
      SERVER_SSL_KEY-STORE-PASSWORD: ${KEYSTORE_PASSWORD}
      OPENBAS_BASE-URL: http://localhost:8080
      OPENBAS_AUTH-LOCAL-ENABLE: true

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/openbas
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      MINIO_ENDPOINT: minio
      MINIO_ACCESS-KEY: ${MINIO_ROOT_USER}
      MINIO_ACCESS-SECRET: ${MINIO_ROOT_PASSWORD}

      OPENBAS_RABBITMQ_HOSTNAME: rabbitmq
      OPENBAS_RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      OPENBAS_RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS}

      # SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      # SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      # SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      # SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE}
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: "*"
      # SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

      # OPENBAS_MAIL_IMAP_ENABLED: ${OPENBAS_MAIL_IMAP_ENABLED}
      # OPENBAS_MAIL_IMAP_HOST: ${OPENBAS_MAIL_IMAP_HOST}
      # OPENBAS_MAIL_IMAP_PORT: ${OPENBAS_MAIL_IMAP_PORT}
      # OPENBAS_MAIL_IMAP_USERNAME: ${SPRING_MAIL_USERNAME}
      # OPENBAS_MAIL_IMAP_PASSWORD: ${SPRING_MAIL_PASSWORD}
      # OPENBAS_MAIL_IMAP_AUTH: ${OPENBAS_MAIL_IMAP_AUTH}
      # OPENBAS_MAIL_IMAP_SSL_ENABLE: ${OPENBAS_MAIL_IMAP_SSL_ENABLE}
      # OPENBAS_MAIL_IMAP_SSL_TRUST: "*"
      # OPENBAS_MAIL_IMAP_STARTTLS_ENABLE: ${OPENBAS_MAIL_IMAP_STARTTLS_ENABLE}

      OPENBAS_ADMIN_EMAIL: ${OPENBAS_ADMIN_EMAIL}
      OPENBAS_ADMIN_PASSWORD: ${OPENBAS_ADMIN_PASSWORD}
      OPENBAS_ADMIN_TOKEN: ${OPENBAS_ADMIN_TOKEN}
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - minio
      - rabbitmq
    restart: unless-stopped
    networks:
      - openbas-default

# # # # # DEPENDENCIES # # # # #

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    expose:
      - 5432
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - openbas-default

  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    # volumes:
    #   - minio:/data
    expose:
      - 9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    restart: unless-stopped
    networks:
      - openbas-default

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_NODENAME: rabbit01@localhost
    # volumes:
    #   - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - openbas-default

# volumes:
#   minio:
#   postgres:
#   rabbitmq:

networks:
  openbas-default:
    driver: bridge
